### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by giuliastro** [MSU-NatSci/DomainAccessibilityAudit#2]
Hello, I created a .env file in the root folder with these informations:

ADMIN_USERNAME=giulio
ADMIN_PASSWORD=12345

And restarted the service with:

docker-compose up -d

Everything starts and it doesn't complain about missing admin password as it would if I don't compile an .env file:

WARNING: The SAML_ENTRYPOINT variable is not set. Defaulting to a blank string.
WARNING: The SAML_ISSUER variable is not set. Defaulting to a blank string.
WARNING: The SAML_CERT variable is not set. Defaulting to a blank string.
WARNING: The SAML_PRIVATE_CERT variable is not set. Defaulting to a blank string.
domainaccessibilityaudit-master_mongodb_1 is up-to-date
Recreating domainaccessibilityaudit-master_accessibility_audit_1 ... done

The problem is that whatever admin user +  password I use I cannot login.

**Comment by dascheaten** [comment]
@giuliastro how did you end up fixing this?  I'm having the same issue.

**Comment by giuliastro** [comment]
@dascheaten you need to remove the container, a simple restart doesn't work. So you first modify / create the .env file, then you create the container and start it. If you already created it you need to remove it and then re-create it. Let me know if it worked for you.

**Comment by dascheaten** [comment]
@giuliastro I was finally able to get it to work.  After uninstalling and reinstalling a few times, I did it finally without the admin_username field and it worked.

**Comment by damien-git** [comment]
Thanks for sharing this.
There was an issue in the latest version of the application, as it was creating an unusable admin user without a password if none was specified. At this point the volume had to be recreated, not just the containers. I added a test to prevent that, so that simply recreating the containers works after modifying the `.env` file. I also added an FAQ question about it.

**Comment by mgifford** [comment]
Could the process be stopped or a warning given if there is no password?

**Comment by fcovecino** [comment]
Hello, 

I'm experimenting with the project (thanks for providing it) and I'm finding that ADMIN_USERNAME in the .env file is not taken into account. The admin username will always be "admin"... ADMIN_PASSWORD works well for setting up the admin password. 

Is anybody seeing the same?

Thanks.
